### ISSUE TITLE
ask dataset

### ISSUE THREAD

**Issue by MingZier** [mengyuest/AR-Net#3]
Hello teacher, I have read your AR-Net article and benefited a lot. But now I have some problems. I can't find the ActivityNet, FCVID and mini-Kinetics datasets. Is it convenient for you to share it? Thank you, teacher!

**Comment by Yao1up** [comment]
> Hello teacher, I have read your AR-Net article and benefited a lot. But now I have some problems. I can't find the ActivityNet, FCVID and mini-Kinetics datasets. Is it convenient for you to share it? Thank you, teacher!

Have you got the ActivityNet dataset? I downloaded it from the official website just a JSON file, rather than videos？

**Comment by Maojianzeng** [comment]
> > Hello teacher, I have read your AR-Net article and benefited a lot. But now I have some problems. I can't find the ActivityNet, FCVID and mini-Kinetics datasets. Is it convenient for you to share it? Thank you, teacher!
> 
> Have you got the ActivityNet dataset? I downloaded it from the official website just a JSON file, rather than videos？

I have got the ActivityNet dataset and shared it on baidu drive. You can get the ActivityNet dataset at here:
https://pan.baidu.com/s/139q4UoIMoW34LhKmyv1TFA 
password:p9zr
It is very large over 700GB so make sure that you have enough space to save it.
