### ISSUE TITLE
Update of the c_x in the policy network

### ISSUE THREAD

**Issue by zhedasuiyuan** [mengyuest/AR-Net#4]
Hi Yue, thanks very much for this very interesting project and your code. I have one question on the implementation of the policy network. 

On [this line](https://github.com/mengyuest/AR-Net/blob/2a9d72b50fed390e58cba6b3af368e3301ec078f/ops/models_ada.py#L328), we will use the old_hx if the frame was skipped. But why do not we also assign the old c_x to c_x here in this case? Is it a bug? Thanks!

**Comment by mengyuest** [comment]
Yes. This is a bug. in nn.LSTMCell, hx is for the hidden state, and cx is for the cell state. Ideally we should also assign the old cx to new cx when "skipping" is selected.
