### ISSUE TITLE
mini-kinetics

### ISSUE THREAD

**Issue by banzhuan37** [mengyuest/AR-Net#6]
Hi there,
I would like to know where can I get  training.csv and validation.csv files for mini-kinetics since I can only find k400 k600 files.

**Comment by mengyuest** [comment]
You can get them from [here](https://drive.google.com/drive/folders/1j7XF86Wq9sNbBwHCIA0lQn1w015CVF4g?usp=sharing)

**Comment by banzhuan37** [comment]
thank u
