### ISSUE TITLE
Frame-rates

### ISSUE THREAD

**Issue by samrudhdhirangrej** [mengyuest/AR-Net#7]
Hello,

Thank you for your excellent work.

I am preparing ActivityNet, FCVID, and MiniKinetics datasets following the [instructions](https://github.com/mengyuest/AR-Net#dataset-preparation) provided in README.md.
I understand that [./ops/video_jpg.py](https://github.com/mengyuest/AR-Net/blob/master/ops/video_jpg.py) extracts frames using ffmpeg which has a default fps of 25. Please correct me if I am wrong.
However, looking at splits provided in the shared [Google Drive](https://drive.google.com/drive/folders/1VbC0uUR6aKeM3AYoRL8rch1rT0wYyq3F), FCVID seems to have fps of ~2.
It would be really helpful if you can provide exact frame rates for the three datasets.

Thank you.

**Comment by hongyunyan** [comment]
您好，邮件已收到！万分感谢！洪韫妍

**Comment by MohamedAfham** [comment]
@mengyuest Looking the answers for the same question. Thanks

**Comment by mengyuest** [comment]
From the log I think I was using `--frame_rate 1` for FCVID, and default frame_rate (25 fps) for ActivityNet and MiniK.
