### ISSUE TITLE
for Fudan-Columbia Video Dataset（FCVID）

### ISSUE THREAD

**Issue by water-hub** [mengyuest/AR-Net#8]
What a wonderful work!
Hello , I have read your paper and benefited a lot. But now I have some problems. I can't find the  Fudan-Columbia Video Dataset（FCVID）and its homepage cannot be accessed anymore . Is it convenient for you to share it? Thank you!

**Comment by mengyuest** [comment]
I am sorry to hear that. Maybe it is better for you to contact the FCVID team members directly. I don't have the right access to those files anymore after my internship.
